# Stage 1: Build
FROM gradle:8.4.0-jdk17-alpine AS builder
WORKDIR /app
COPY . .
RUN gradle build --no-daemon

# Stage 2: Run
FROM openjdk:17-jdk-alpine
WORKDIR /app
COPY --from=builder /app/build/libs/*.jar app.jar
EXPOSE 9090
ENTRYPOINT ["java", "-jar", "app.jar"]
